### ISSUE TITLE
Mongoid version restriction too high

### ISSUE THREAD

**Issue by brennana** [ElMassimo/mongoid_includes#12]
`mongoid_includes` v2.0.0 fixed eager loading issues that arose from changes in mongoid 5 and 6. However, `mongoid_includes` now requires mongoid 6, which stops users on mongoid 5 (and hence rails 4) from using this gem, even though it should still work with mongoid 5, given the main difference between 5 and 6 is their rails support.

`mongoid_includes` should still be able to support mongoid >= 5.2.0.

**Comment by ElMassimo** [comment]
Because of the changes in mongoid _6.0.1_, it would be cumbersome to support both versions at the same time.

However, that shouldn't be an issue, since you can still use _1.1.3_ with mongoid 5.

I intend to backport any bugfixes if necessary  (and release _1.1.4_, for example), since I'm still using mongoid 5 in production 😃
