### ISSUE TITLE
Scope with limit not working

### ISSUE THREAD

**Issue by alaouy** [ElMassimo/mongoid_includes#7]
Hello there!
I tried using the gem to eager load some users with their posts using a limit scope but it didn't work
Something like this :
```ruby
User.includes(:posts, with: ->(posts) { posts.where(approved: true).limit(10) })
```
The snippet above returns only the 10 posts for the first user and empty results for the rest of the users

Is there a fix for this or I'm doing something wrong ?

**Comment by ElMassimo** [comment]
That behaviour is expected, since the `posts` query is a batch query to get posts for all the users, it's not limited to a particular user (otherwise it would trigger N+1 queries).

What's happening with the snippet above is that the total batch is being limited to `10`, which happen to belong to a single user, but could also return a few posts for a few different users.

I'm not aware of a way to perform a single query to achieve what you need using Mongoid, perhaps if you use the aggregation framework starting from those, and then create `Post` instances from the results and return them in that block you will achieve the desired effect, but I haven't tried anything similar.

```ruby
User.includes(:posts, with: ->(posts) { restrict_posts_by_user(posts) })

# Just pseudo-code, not sure if you can actually pull that off with a single query.
def restrict_posts_by_user(posts)
  aggregated_posts = posts.group(_id: '$author_id')...aggregate
  aggregated_posts.map { |doc| Post.new(doc) }
end
```

Check [this post](http://maximomussini.com/posts/mongoid-aggregation-dsl/) for a quick tip on how to leverage Mongoid's DSL for aggregation.
